version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          touch .env 
          echo SKIP_PREFLIGHT_CHECK=true >> .env
      - run: npm test
deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "0f:c3:e6:6a:5d:20:fc:41:31:ef:9d:a1:f2:f1:17:91"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/sb242/scheduler.git master:production
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
